name: CI    # название скрипта: будет отображаться во вкладке Actions

on: [push]  # действие, по которому запускается данный скрипт

jobs:       # роботы, которые будут выполняться
  build:    # сборка, которая..

    runs-on: ubuntu-latest    # ..будет запущена на основе этого образа

    steps:    # шаги которые будут проделаны после запуска образа
    - uses: actions/checkout@v1         # переход в самую актуальную ветку
    - name: Set up Python               # Установка питона
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies        # Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests                   # Запуск тестов
      run: coverage run talk_with_me/test.py
    - name: Tests report                # Покрытие тестами
      run: |
        coverage xml
        bash <(curl -s https://codecov.io/bash) -t 9393fc09-5527-46ff-8086-85221f6c8890
    - name: black
      run: black talk_with_me/
    - name: black check        # Проверка форматирования кода
      run: black --check talk_with_me/
    - name: Commit files
      run: |
        REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git pull ${REMOTE}
        git checkout master
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "ci: Automated build push" -a | exit 0
        git push ${REMOTE} master
    - name: Push changes
      
